// <auto-generated />
namespace GoSharpRest.Migrationsas
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class NewReferences : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NewReferences));
        
        string IMigrationMetadata.Id
        {
            get { return "201804071829539_New References"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
